### PR TITLE
chore: test example

### PR DESCRIPTION
**Pull request by kjappelbaum**

### CODE REVIEW

**Comment by kjappelbaum** [comment]
perhaps not that important ;) 

but a good time for a new release :)

**Comment by kjappelbaum** [comment]
perhaps we should run simply doctest on the readme ...

**Comment by sgbaird** [comment]
Reran the tests and it was fine (maybe you noticed the "coveralls busy" error). Ok to merge?

**Comment by kjappelbaum** [comment]
let me check if it actually ran the doctests on the README :)

**Comment by sgbaird** [comment]
No rush. Thx!

**Comment by kjappelbaum** [comment]
the stuff that `m3gnet` printed to stdout threw the doctest off. Works now. If you're fine with the changes, it's ready to merge.

**Pull request merged**
